config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'my_passwords', to: 'passwords#my_passwords'
  get 'search_password', to: 'passwords#search'
  devise_for :users, :controllers => { :registrations => 'registrations'}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users
  resources :passwords
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/password.rb
class Password < ApplicationRecord
	# validates :name, presence: true
	# validates :user_name, presence: true
	#belongs_to :user

	def self.matches(field_name, param) 
		Password.where("#{field_name} like ?", "%#{param}%")
	end

	def self.search(param)
		param.strip!
		to_send_back = name_matches(param).uniq
		return nil unless to_send_back
		to_send_back
	end

	def self.name_matches(param) 
		matches('cast(name as text)', param)
	end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :passwords
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authorize_admin
    redirect_to root_path, alert: 'Access Denied' unless current_user.admin?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
   def home
       
   end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!
  def index
    @passwords = Password.all
  end

  def search 
    if params[:name].present?
      @passwords = params[:name].present?
      @passwords = Password.search(params[:name])
      if @passwords && @passwords.count > 0
        respond_to do |format|
        format.js { render partial: 'passwords/password_result' }
      end
      else
        respond_to do |format|
        flash.now[:danger] = "There are no result's found for this request.."
        format.js { render partial: 'passwords/password_result' }
      end
      end
    else
      respond_to do |format|
      flash.now[:alert] = "Please enter a Name"
      format.js { render partial: 'passwords/password_result' }
      end
    end
  end
    
  def new
    @password = Password.new
  end
  
  def create
    @password = Password.new(password_params)
    if @password.save
      flash[:success] = "Password Details Saved"
      redirect_to password_path(@password)
    else
      render 'new'
    end
  end
  
  def show
    @password = Password.find(params[:id])
  end
  
  def edit
    @password = Password.find(params[:id])
  end

  def update
    @password = Password.find(params[:id])
    if @password.update(password_params)
      flash[:success] = "Password details updated"
      redirect_to password_path(@password)
    else
      render 'edit'
    end
  end

  def destroy
    @password = Password.find(params[:id])
    @password.destroy
    flash[:danger] = "Password Deleted"
    redirect_to passwords_path
  end
  
  
  
  private
  
  def password_params
    params.require(:password).permit(:name, :user_name, :password, :groups, :notes)
  end

  def require_same_user
    if current_user != @password.user and !current_user.admin?
      flash[:danger] = "You cannot Edit or delete this Password"
      redirect_to passwords_path
    end
  end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!, :redirect_unless_admin,  only: [:new, :create]
  skip_before_action :require_no_authentication

  private
  def redirect_unless_admin
    unless current_user.try(:admin?)
      flash[:error] = "Only admins can do that"
      redirect_to root_path
    end
  end

  def sign_up(resource_name, resource)
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin
  
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def create
    # @user= User.new(user_params)
    # if @user.save
    #   flash[:success] = "Details Created"
    #   redirect_to users_path(@user)
    # else
    #   flash[:danger] = "Try Again.."
    #   render 'new'
    # end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      # flash.now[:success] "Updated"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    if @user.destroy
      flash.now[:success] = "User Deleted"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_linebreaks(text)
    safe_text = h(text)
    paragraphs = split_paragraphs(safe_text).map(&:html_safe)
  
    html = ''.html_safe
    paragraphs.each do |paragraph|
      html << content_tag(:p, paragraph)
    end
    html
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class="row">

    <div class="col-md-10 col-md-offset-1">
    
        <% flash.each do |name, msg| %>
        
            <div class="alert alert-<%= name %>">
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= msg %>
            </div>
        
        <% end %>
    
    </div >

</div >

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top bg-green">
    <div class="container">
      <nav>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button> 
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-left">
                <li><%= link_to "Home", root_path %></li>
                
                <% if current_user %>
                  <li><%= link_to "Password Index", passwords_path, class: "btn btn-purple nav-but" %></li>
                  <li class="white"><%= link_to current_user.name if current_user %></li>
                  <li><%= link_to "(Admin)" if current_user.admin? %></li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><%#= link_to "Help", help_path %></li>
                <% if current_user && current_user.admin? %>
                  <li><%= link_to "Users", users_path, class: "btn btn-warning nav-but" %></li>
                  <li><%= link_to "New User", new_user_registration_path, class: "btn btn-success nav-but" %></li>
                  <li><%= link_to "New Password", new_password_path, class: "btn btn-primary nav-but" %></li>
                <% end %>
                <% if current_user %>
                  <li><%= link_to "Log out", destroy_user_session_path, class: "btn btn-danger nav-but", method: :delete %></li>
                    <li></li>
                <% else %>
                  <li><%= link_to "Log in", new_user_session_path, class: "btn btn-primary nav-but", method: :get %></li>
                <% end %>
            </ul>
        </div>
      </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VincePasswords</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv=“X-UA-Compatible” content=“IE=edge”>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/flash' %>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="jumbotron">
        <h1 class="text-center">Password App</h1>
    </div>
    <% if current_user %>
        <p class="text-center"><%= link_to "Change Your Password", edit_user_registration_path, class: "btn btn-warning btn-lg" %></p>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="text-center">
    <div class="col-md-8 col-md-offset-2">
      <% @users.each do |user| %>
        <div class="well profile-black-white-thin row" <%= cycle("profile-black-white-thin-b", '') %> 

              <p></p>    
							<p class="bold-white"> Name:  <span class="white"><%= user.name %><%= " (Admin)" if user.admin?%></span></p>
							<p class="bold-white"> User Name:  <span class="white"><%= user.email %> </p>
							<p class="spacer">Bubble</p>
              
							<%= link_to "View", user_path(user), class: "btn btn-warning" %> 
							<% if current_user && current_user.admin? %>
									<%= link_to "Edit", edit_user_registration_path(user), class: "btn btn-primary" %>
							<% end %>
              <% if current_user.admin? && !user.admin? %>
                <%= link_to "Delete", admin_destroy_user_path(user), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger" %> 
              <% end %>
            
         </div>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class ="center well">
    <h2 class="text-center">User Details for: <%= @user.name %></h2>
    <h3 class="text-center">User: <%= current_user.name %> <%= " 'Admin User'" if current_user.admin?%>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
          <p><span class="bold-white">User Name:  </span><span class="white"><%= @user.name %></span></p>
          <p><span class="bold-white">Email:  </span><span class="italics"><%= @user.email %></span></p>

        <div class="text-center">
          <% if current_user && current_user.admin? %>
          <%= link_to "Edit User Details", edit_user_registration_path(@password), class: "btn btn-warning" %>
          <% end %>
          <%= link_to "Back to Index", passwords_path, class: "btn btn-success" %> 
        </div>
      </div>
    </div>
  </div>
</div>